apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  # Optional if you need regex paths
spec:
  ingressClassName: nginx  # Correct way to set the Ingress class
  rules:
    - host: update-host-name.com  # Replace with your valid hostname
      http:
        paths:
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: payments-srv
                port:
                  number: 4000
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: auths-srv
                port:
                  number: 4000
          - path: /api/tickets
            pathType: Prefix
            backend:
              service:
                name: tickets-srv
                port:
                  number: 4000
          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: orders-srv
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000

