name: deploy-manifests 

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_ACCESS_TOKEN }}

      - name: Set up Kubernetes configuration
        run: doctl kubernetes cluster kubeconfig save ticketing

      - name: Apply all infra config files
        run: kubectl apply -f infra/k8s
